spring.application.name=CodeMate

spring.profiles.default=h2

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

codemate.jwt.secret=${CODEMATE_JWT_SECRET:Y29kZW1hdGUtand0LXNlY3JldC1rZXktZm9yLWxvY2FsLWRldmVsb3BtZW50}
codemate.jwt.access-token-validity-milliseconds=3600000

springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
